name: wekan-ondra
version: "0.11.1-rc2"
summary: The open-source Trello-like kanban
description: |
   Wekan is an open-source and collaborative kanban board application.

   Whether you’re maintaining a personal todo list, planning your holidays with some friends, or working in a team on your next revolutionary idea, Kanban boards are an unbeatable tool to keep your things organized. They give you a visual overview of the current state of your project, and make you productive by allowing you to focus on the few items that matter the most.
   Depending on target environment, some configuration settings might need to be adjusted.
   For full list of configuration options call:
   $ wekan-ondra.help

confinement: strict
grade: stable

apps:
    wekan:
        command: wekan-control start_node
        daemon: simple
        plugs: [network, network-bind]

    mongodb:
        command: mongodb-control
        daemon: simple
        plugs: [network, network-bind]

    start:
        command: wekan-control start
        plugs: [network, network-bind]

    stop:
        command: wekan-control stop
        plugs: [network, network-bind]

    status:
        command: wekan-control status
        plugs: [network, network-bind]

    restart:
        command: wekan-control restart
        plugs: [network, network-bind]

    help:
        command: wekan-help help

parts:
    mongodb:
        source: https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1604-3.2.10.tgz
        plugin: dump
        stage-packages: [libssl1.0.0]
        filesets:
            mongo:
                - usr
                - bin
                - lib
        stage:
            - $mongo
        prime:
            - $mongo

    wekan:
        source: https://github.com/wekan/wekan/releases/download/v0.11.1-rc2/wekan-0.11.1-rc2.tar.gz
        source-subdir: programs/server
        plugin: nodejs
        node-packages: [npm]
        node-engine: 0.10.48
        build-packages:
            - python
        install: |
            cp -r * $SNAPCRAFT_PART_INSTALL/
            cp .node_version.txt $SNAPCRAFT_PART_INSTALL/
        organize:
            README: README.wekan

    helpers:
        source: src
        plugin: dump
        organize:
            wekan-control: bin/wekan-control
            mongodb-control: bin/mongodb-control
            wekan-read-settings: bin/wekan-read-settings
            wekan-help: bin/wekan-help
            config: bin/config
            configure: meta/hooks/configure
